version: "3.9"
services:
  bot:
    build: ./
    container_name: bot
    restart: always
    command: ["yarn", "serve"]
    env_file: .env
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules/
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - data:/data/db

volumes:
  data:
